# Generated by Django 5.0 on 2024-11-11 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('name', models.CharField(max_length=55)),
                ('name2', models.CharField(max_length=55)),
                ('addtion', models.CharField(max_length=55)),
                ('image', models.ImageField(upload_to='banner_imageh')),
                ('image2', models.ImageField(upload_to='banner_imageh2')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('profeccion', models.CharField(max_length=55)),
                ('own', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surename', models.CharField(max_length=25)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('price', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='pricing_image/')),
                ('traffic1', models.CharField(max_length=155)),
                ('traffic2', models.CharField(max_length=155)),
                ('traffic3', models.CharField(max_length=155)),
                ('traffic4', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(max_length=155)),
                ('facebook', models.CharField(max_length=155)),
                ('inlink', models.CharField(max_length=155)),
                ('instagramm', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('profeccion', models.CharField(max_length=55)),
                ('about', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('addition', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=155)),
                ('Image', models.ImageField(upload_to='About_image/')),
                ('advantages', models.ManyToManyField(to='main.advantages')),
            ],
        ),
        migrations.CreateModel(
            name='Choose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('addition', models.CharField(max_length=155)),
                ('Image', models.ImageField(upload_to='image_choose/')),
                ('service', models.ManyToManyField(to='main.advantages')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('addition', models.CharField(max_length=55)),
                ('service', models.ManyToManyField(to='main.service')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('email', models.CharField(max_length=155)),
                ('call_us', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_number', message='Invalid phone number', regex='^[\\+]9{2}8{1}[0-9]{9}$')])),
                ('description', models.CharField(max_length=255)),
                ('social', models.ManyToManyField(to='main.social')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_image/')),
                ('name', models.CharField(max_length=55)),
                ('job', models.CharField(max_length=55)),
                ('social', models.ManyToManyField(to='main.social')),
            ],
        ),
    ]
