# Generated by Django 5.0 on 2024-11-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='name2',
        ),
    ]
