# Generated by Django 5.0 on 2024-11-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_banner_image2_remove_banner_name2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner_image/'),
        ),
    ]
