# Generated by Django 5.0 on 2024-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image2',
            field=models.ImageField(default=1, upload_to='banner_imageh2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner_imageh'),
        ),
    ]
