# Generated by Django 5.0 on 2024-11-13 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_banner_image2_alter_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
