# Generated by Django 5.0 on 2024-11-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='advantages',
        ),
        migrations.AddField(
            model_name='about',
            name='Image2',
            field=models.ImageField(default=1, upload_to='About_image2/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='Image3',
            field=models.ImageField(default=1, upload_to='About_image3/'),
            preserve_default=False,
        ),
    ]
