# Generated by Django 5.0 on 2024-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_about_advantages_about_image2_about_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='About_image/')),
                ('Image2', models.ImageField(upload_to='About_image2/')),
                ('Image3', models.ImageField(upload_to='About_image3/')),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='Image3',
        ),
    ]
