# Generated by Django 5.0 on 2024-11-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_image_remove_about_image_remove_about_image2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(default=1, upload_to='About_image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image2',
            field=models.ImageField(default=1, upload_to='About_image2/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='image3',
            field=models.ImageField(default=1, upload_to='About_image3/'),
            preserve_default=False,
        ),
    ]
