# Generated by Django 5.0 on 2024-11-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_image_about_image_about_image2_about_image3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choose',
            old_name='Image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='choose',
            name='service',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner_imageh/'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image2',
            field=models.ImageField(upload_to='banner_imageh2/'),
        ),
    ]
