# Generated by Django 5.0 on 2024-11-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_image_choose_image_remove_choose_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='social',
        ),
        migrations.AddField(
            model_name='team',
            name='social',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.social'),
            preserve_default=False,
        ),
    ]
