# Generated by Django 5.0 on 2024-11-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_team_social_team_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='traffic1',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='traffic2',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='traffic3',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='traffic4',
        ),
        migrations.AddField(
            model_name='pricing',
            name='boarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='feeding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='spa_grooming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='veterinary_medicine',
            field=models.BooleanField(default=False),
        ),
    ]
