# Generated by Django 5.0 on 2024-11-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_pricing_traffic1_remove_pricing_traffic2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default=1, upload_to='Image_testimonial/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.FloatField(),
        ),
    ]
