# Generated by Django 5.0 on 2024-11-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_testimonial_image_alter_pricing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='profeccion',
            new_name='profession',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_image/'),
            preserve_default=False,
        ),
    ]
