# Generated by Django 5.0 on 2024-11-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_profeccion_blog_profession_blog_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
